### ISSUE TITLE
height of <br> elements

### ISSUE THREAD

**Issue by samoht** [ocamllabs/opam-doc#45]
If you compare:
http://erratique.ch/software/cmdliner/doc/Cmdliner
and
http://ocaml-redesign.github.io/pkg/docs/?package=cmdliner&module=Cmdliner

you'll see a bunch of differences in the way the text is displayed. Especially, it seems that `<br>` elements are missing some height in `opam-doc` (and the code is not colorized properly, but I think this is tracked in an other issue).

**Comment by samoht** [comment]
Also the text on `ocaml-redisign` is stacked on the right instead of being stacked on the left as on Daniel's website.

**Comment by pw374** [comment]
Actually, it's not really a question of br heights... those `<br/>`s should be paragraphs (in `<p>`s)!

The text being stacked to the right is "normal", it's copied from standard ocamldoc design, e.g., http://caml.inria.fr/pub/docs/manual-ocaml/libref/List.html

**Comment by samoht** [comment]
Regarding the `<br>`: maybe in the ideal world these should beparagraph, but if you want to support existing doc I guess you have to make some compromise ...

Regarding the left/righ align: I'm not totally convinced by the 80-columns display but if we stick with that (instead of the nice "full text" page you gave from the current ocamldoc design), I don't really understand why we also want a big and empty left column. Or maybe you want to add a table of contents on the left as well.

**Comment by samoht** [comment]
(see for instance http://www.ocamlpro.com/doc/stdlib/Arg.html the design we started to prototype a couple of years ago)

**Comment by samoht** [comment]
(or also see Haskell's doc generator: http://www.haskell.org/ghc/docs/latest/html/libraries/base-4.6.0.1/Data-String.html#t:String)

**Comment by pw374** [comment]
- `br` vs `p`: It's not a question of "ideal world", ocamldoc produces paragraphs! cf. http://erratique.ch/software/cmdliner/doc/Cmdliner ;-)
  I'll fix this this week unless I forget.
- left/righ align / 80-column display: actually I don't like it the way it is currently. And I don't think it's even 80-column display, it's just some bootstrap-weird-dynamic-narrow-box thingy. But I think making it fullpage doesn't make sense either. We should find a compromise. Also, just to make it clear, it's not an actual opam-doc issue, as you can see the HTML produced by opamdoc is like this http://ocaml-redesign.github.io/pkg/docs/ocaml/Arg.html ;-) So you should open an issue on https://github.com/ocamllabs/sandbox-ocaml.org/ (otherwise I'll do it, unless I forget...)

**Comment by pw374** [comment]
Opamdoc now produces the same structure as ocamldoc, as far as I know, so there are paragraphs instead of line-breaks. (8cfbb2d8b783c7e3359213fe7d899c4dc1c254b5)

On http://ocaml-redesign.github.io/pkg/docs/?package=cmdliner&module=Cmdliner we can still see that there's a problem of height for the part preceding the first paragraph. So I can either make the first part a paragraph, in which case it will differ from ocamldoc's output, or fix the CSS on the ocaml-redesign.github.io part. I'll start by fixing the CSS. And then, if someone has arguments for opamdoc's output to be different than ocamldoc's, please comment below (or open a new issue).

Personally, I think it would be better to have a new paragraph for the first part because it would be more consistent. However, maybe changing that would break some existing stuff, I don't know...
